### ISSUE TITLE
Review the Nevermined documentation

### ISSUE THREAD

**Issue by aaitor** [nevermined-io/docs#14]
The following issue includes:

- [x] Review the existing nevermined docs sections regarding the sdks
- [x] Compare the state of the Js, Py and Java versions of the SDKs
- [x] Generate a unified SDK structure
- [x] Modify the SDK's to use the new structure
- [x] Document the SDKs APIs
- [x] CLI Documentation
